Email transcript use case
Callhub-Connect/callhub-frontend pull request #34
Opened 2023-11-27 03:44 UTC by lucieyang1

# Description
- Gets the messages from the session and formats it into a transcript string

Fixes # (issue)
- SessionId and SessionCode no longer get removed from the session storage, is that ok?

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Manually tested. Make sure to get the associated backend branch for code review.
<img width="352" alt="image" src="https://github.com/Callhub-Connect/callhub-frontend/assets/85754817/ce6911bd-1265-4137-8f9d-b2eb5026a079">

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code

2023-11-27 08:10 UTC, zjayee reviewed
I've checked out the branch and the email transcript sending works on my end! Overall, coding is clear and follows style conventions. Just one question about the api.

2023-11-27 08:10 UTC, zjayee commented on src/components/EndSession.jsx
> +    useEffect(() => emailjs.init("OScF2lHq5ESl_o9lU"), []);
Are these api keys? If they are, they should be moved to the environment variables.

2023-11-27 08:10 UTC, zjayee commented on src/components/Chat.jsx
> -    sessionStorage.removeItem("sessionCode")
If sessionId and sessionCode are not cleared here, there should be code in end session somewhere that clears them when the session ends. Perhaps when the user clicks on a return to home/start button. However, that may be out of the scope of this PR.

2023-11-27 18:39 UTC, zjayee commented on src/components/EndSession.jsx
> +    useEffect(() => emailjs.init("OScF2lHq5ESl_o9lU"), []);
Oh if it's a public api then it's fine. I thought it was private one.

2023-11-27 18:53 UTC, sarinali commented on src/components/EndSession.jsx
> +    useEffect(() => emailjs.init("OScF2lHq5ESl_o9lU"), []);
I think we should use environment variable for this

2023-11-27 18:54 UTC, sarinali reviewed
LGTM, minor comment

2023-11-27 19:07 UTC, 3milyfz requested changes
Good job! Just a minor comment on use of alert.

2023-11-27 19:07 UTC, 3milyfz commented on src/components/EndSession.jsx
> +            alert("Oops! Something went wrong while trying to send the email. Please make sure there are messages in the conversation before sending.");
Can you change the alerts to mui alerts to stay consistent with the ones in my pull request? 
- This is the documentation: https://mui.com/material-ui/react-alert/
- You can reference my pr to see how to make them disappear automatically after a certain amount of time so users don't need to close it

2023-11-28 05:49 UTC, lucieyang1 commented on src/components/EndSession.jsx
> +    useEffect(() => emailjs.init("OScF2lHq5ESl_o9lU"), []);
I tried putting the key into an .env file, but for some reason, it shows up as undefined when I try to run the code. There might be something wrong with what I'm doing, though I searched google and it seems like someone had the same issue 2 years ago, that went unresolved: https://stackoverflow.com/questions/66491790/why-can-t-i-send-messages-with-emailjs-when-hiding-my-keys-in-env

2023-11-30 05:31 UTC, 3milyfz approved these changes
LGTM!

2023-11-30 05:48 UTC, merged